// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Milktea.Repository.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public string AccountPassword { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public int AccountRole { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}