// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Milktea.Repository.Models;

public partial class ComboProduct
{
    public int ComboProductId { get; set; }

    public int IncludedProductId { get; set; }

    public int? Quantity { get; set; }

    public virtual Product ComboProductNavigation { get; set; }

    public virtual Product IncludedProduct { get; set; }
}