// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Milktea.Repository.Models;

public partial class Combo
{
    public int ComboId { get; set; }

    public string ComboName { get; set; }

    public decimal? ComboPrice { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public int? ProductId1 { get; set; }

    public int? ProductId2 { get; set; }

    public int? ProductId3 { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product ProductId1Navigation { get; set; }

    public virtual Product ProductId2Navigation { get; set; }

    public virtual Product ProductId3Navigation { get; set; }
}