// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.Milktea.Repository.Models;

public partial class ComboProduct
{
    public int ComboId { get; set; }

    public int ProductId { get; set; }

    public int? Quantity { get; set; }

    public virtual Combo Combo { get; set; }

    public virtual Product Product { get; set; }
}